### ISSUE TITLE
Resend Button | Edit Prompt

### ISSUE THREAD

**Issue by debabrata100** [vikash-bhardwaj/ai-code-companion-documentation#1]
It would be great if we can have a **Resend** button or **Edit** button for prompt, when there is a api time out or for some reason api fails, So that we do not have to copy paste our entire prompt again. 

Thanks

**Comment by vikash-bhardwaj** [comment]
Thanks @debabrata100 for bringing this and I have also thought about this couple of time, will add this in next version

**Comment by vikash-bhardwaj** [comment]
Hi @debabrata100  - I have published a new version 1.6.0 where both Edit Prompt and Repeat last prompt is added so closing this issue
