### ISSUE TITLE
API call

### ISSUE THREAD

**Issue by ashik529** [vikash-bhardwaj/ai-code-companion-documentation#4]
Hi. I am facing another issues
![api](https://github.com/vikash-bhardwaj/ai-code-companion-documentation/assets/149458880/84fe4ed0-2c80-4cf0-810e-d42edfadf050)

**Comment by vikash-bhardwaj** [comment]
Hi,

You generally get this issue if you are not working with a Paid account and
OpenAI account is not set-up for its usage and limit. If you have a paid
account with OpenAI then this error shouldn't appear, let me know if this
is helpful.

Thanks
Vikash

**Comment by vikash-bhardwaj** [comment]
Hi @ashik529 - Hope your issues resolved so can I mark the issues as closed?

**Comment by vikash-bhardwaj** [comment]
Closing this issue as no response and it's working for other users.
