### ISSUE TITLE
Is there a corresponding plugin for IntelliJ too?

### ISSUE THREAD

**Issue by lakshminarayanat** [vikash-bhardwaj/ai-code-companion-documentation#5]
Just trying to understand do we have a similar plugin for IntelliJ too.

**Comment by vikash-bhardwaj** [comment]
hey @lakshminarayanat - I am sorry fro delayed response but for now no, we dont have this available for IntelliJ and if we plan to launch one then for sure will update

**Comment by vikash-bhardwaj** [comment]
if you work on IntelliJ a lot and wish you contribute one then we can work on creating one similar to this :)

**Comment by vikash-bhardwaj** [comment]
I am closing this issue and for anything else wrt to this topic you can send a message on Discord and my user name is "iamvikashbhardwaj" for faster responses :)
